Imported Upstream version 2.0.0

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -7,10 +7,21 @@
 ##  Authors: Sam Hocevar <sam@zoy.org>
 ##           Rémi Denis-Courmont <rem # videolan # org>
 
+set -e
+
+cd "$(dirname "$0")"
+
 if test "$#" != "0"; then
   echo "Usage: $0"
   echo "  Calls autoreconf to generate m4 macros and prepare Makefiles."
   exit 1
+fi
+
+ACLOCAL_ARGS="-I m4 ${ACLOCAL_ARGS}"
+
+# Check for tools directory
+if test -d extras/tools/build/bin; then
+  PATH="`pwd`/extras/tools/build/bin:$PATH"
 fi
 
 ###
@@ -18,17 +29,6 @@ fi
 ###
 CYGWIN=binmode
 export CYGWIN
-
-set -e
-set -x
-
-cd "$(dirname "$0")"
-
-##
-## Check for various tools
-##
-
-ACLOCAL_ARGS="-I m4 ${ACLOCAL_ARGS}"
 
 # Check for contrib directory
 if test -d extras/contrib/build/bin; then
@@ -41,71 +41,55 @@ if test -d extras/contrib/build/bin; then
     DYLD_LIBRARY_PATH=./extras/contrib/build/lib:$DYLD_LIBRARY_PATH
     export LD_LIBRARY_PATH
     export DYLD_LIBRARY_PATH
-  elif test ".`uname -s`" = ".BeOS"; then
-    LIBRARY_PATH=./extras/contrib/build/lib:$LIBRARY_PATH
-    BELIBRARIES=./extras/contrib/build/lib:$BELIBRARIES
-    export LIBRARY_PATH
-    export BELIBRARIES
   fi
-elif test ".`uname -s`" = ".Darwin"; then
-  set +x
-  echo ""
-  echo "ERR: Contribs haven't been built"
-  echo "ERR: Please run:"
-  echo "ERR: "
-  echo "ERR:    'cd extras/contrib && ./bootstrap && make && cd ../..'"
-  echo "ERR: "
-  echo "ERR: Make sure fink has been disabled too."
-  echo ""
-  set -x
-  exit 1
 fi
 
 # Check for pkg-config
-if pkg-config --version >/dev/null 2>&1; then
-  # We have pkg-config, everything is cool.
-  PKGCONFIG=yes
-else
-  PKGCONFIG=no
+if ! "${PKG_CONFIG:-pkg-config}" --version >/dev/null 2>&1; then
+	echo 'Error: "pkg-config" is not installed.' >&2
+	exit 1
 fi
+
+# Prepare m4/private.m4
+rm -f m4/private.m4 && cat > m4/private.m4 << EOF
+dnl  Private VLC macros - generated by bootstrap
+EOF
 
 # Check for autopoint (GNU gettext)
 export AUTOPOINT
 test "$AUTOPOINT" || AUTOPOINT=autopoint
 if ! "$AUTOPOINT" --dry-run --force >/dev/null 2>&1; then
-  AUTOPOINT=true
-  echo > ABOUT-NLS
+	AUTOPOINT=true
+	cat << EOF
+NOTE: GNU gettext appears to be missing or out-of-date.
+Please install or update GNU gettext.
+Also check if you have cvs, a dependency of autopoint.
+Otherwise, you will not be able to build a source tarball.
+==============================================================
+
+EOF
 fi
 
-##
-## Generate the modules makefile, by parsing modules/**/Modules.am
-##
+###
+### Generate the modules makefile, by parsing modules/**/Modules.am
+###
 
-set +x
 echo "generating modules/**/Makefile.am"
+find modules/ -name Modules.am | \
+sed -ne 's,modules/\(.*\)/Modules.am,\1,p' | \
+while read d; do
+	sh modules/genmf "$d"
+	printf "."
+done
+printf "\n"
 
-# Prepare m4/private.m4
-rm -f m4/private.m4 && cat > m4/private.m4 << EOF
-dnl  Private VLC macros - generated by bootstrap
-
-EOF
-
-if [ "${PKGCONFIG}" = "no" ]; then cat >> m4/private.m4 << EOF
-dnl  User does not have pkg-config, so assume package was not found
-AC_DEFUN([PKG_CHECK_MODULES],[ifelse([\$4], , :, [\$4])])
-
-EOF
-fi
-
-sh modules/genmf `sed -ne 's,modules/\(.*\)/Makefile,\1,p' configure.ac`
+set -x
 
 ###
 ###  classic bootstrap stuff
 ###
-set -x
 
 # Automake complains if these are not present
-echo > vlc-config.in
 echo > ABOUT-NLS
 cp -f INSTALL INSTALL.git
 
@@ -117,34 +101,8 @@ mv -f INSTALL.git INSTALL
 ##
 ##  files which need to be regenerated
 ##
-rm -f vlc-config.in vlc-config
-rm -f src/misc/modules_builtin.h
-rm -f stamp-builtin stamp-h* mozilla/stamp-pic
+rm -f stamp-h*
 
 # Shut up
 set +x
-
-##
-##  Tell the user about gettext, pkg-config and sed
-##
-if [ "$AUTOPOINT" = "true" ]; then
-  cat << EOF
-
-==============================================================
-NOTE: GNU gettext appears to be missing or out-of-date.
-Please install or update GNU gettext.
-Also check if you have cvs, a dependency of autopoint.
-Otherwise, you will not be able to build a source tarball.
-EOF
-fi
-
-if [ "$PKGCONFIG" = "no" ]; then
-  cat << EOF
-
-==============================================================
-NOTE: "pkg-config" is missing from your system. Certain
-libraries may not be detected properly.
-EOF
-fi
-
 echo "Successfully bootstrapped"
