New upstream version 3.0.5

diff --git a/extras/tools/bootstrap b/extras/tools/bootstrap
--- a/extras/tools/bootstrap
+++ b/extras/tools/bootstrap
@@ -24,6 +24,26 @@ then
 	exit 1
 fi
 
+check_version() {
+    gotver=$2
+    gotmajor=`echo $gotver|cut -d. -f1`
+    gotminor=`echo $gotver|cut -d. -f2`
+    gotmicro=`echo $gotver|cut -d. -f3`
+    [ -z "$gotmicro" ] && gotmicro=0
+    needmajor=`echo $3|cut -d. -f1`
+    needminor=`echo $3|cut -d. -f2`
+    needmicro=`echo $3|cut -d. -f3`
+    [ -z "$needmicro" ] && needmicro=0
+    if [ "$needmajor" -ne "$gotmajor" \
+         -o "$needmajor" -eq "$gotmajor" -a "$needminor" -gt "$gotminor" \
+         -o "$needmajor" -eq "$gotmajor" -a "$needminor" -eq "$gotminor" -a "$needmicro" -gt "$gotmicro" ]
+    then
+        echo "$1 too old"
+        NEEDED="$NEEDED .$1"
+    fi
+
+}
+
 check_tar() {
 if ! tar PcJ /dev/null >/dev/null 2>&1
 then
@@ -43,6 +63,19 @@ then
 fi
 }
 
+check_nasm() {
+if ! nasm -v >/dev/null 2>&1
+then
+    echo "nasm not found"
+    NEEDED="$NEEDED .nasm"
+else
+    # found, need to check version ?
+    [ -z "$1" ] && return # no
+    gotver=`nasm -v | cut -d ' ' -f 3`
+    check_version nasm $gotver $1
+fi
+}
+
 check() {
 if ! $1 --version >/dev/null 2>&1 && ! $1 -version >/dev/null 2>&1
 then
@@ -52,21 +85,7 @@ else
     # found, need to check version ?
     [ -z "$2" ] && return # no
     gotver=`$1 --version | head -1 | sed s/'.* '//`
-    gotmajor=`echo $gotver|cut -d. -f1`
-    gotminor=`echo $gotver|cut -d. -f2`
-    gotmicro=`echo $gotver|cut -d. -f3`
-    [ -z "$gotmicro" ] && gotmicro=0
-    needmajor=`echo $2|cut -d. -f1`
-    needminor=`echo $2|cut -d. -f2`
-    needmicro=`echo $2|cut -d. -f3`
-    [ -z "$needmicro" ] && needmicro=0
-    if [ "$needmajor" -ne "$gotmajor" \
-         -o "$needmajor" -eq "$gotmajor" -a "$needminor" -gt "$gotminor" \
-         -o "$needmajor" -eq "$gotmajor" -a "$needminor" -eq "$gotminor" -a "$needmicro" -gt "$gotmicro" ]
-    then
-        echo "$1 too old"
-        NEEDED="$NEEDED .$1"
-    fi
+    check_version $1 $gotver $2
 fi
 }
 
@@ -85,8 +104,11 @@ check ant
 check xz
 check bison 3.0.0
 check flex
+check_nasm 2.13.01
+check meson 0.48.1
+check ninja
 
-[ -n "$NEEDED" ] && mkdir -p build/ && echo "To-be-built packages: `echo $NEEDED | sed 's/\.//g'`"
+[ -n "$NEEDED" ] && mkdir -p build/bin && echo "To-be-built packages: `echo $NEEDED | sed 's/\.//g'`"
 
 CPUS=
 case `uname` in
