git-debimport vlc_0.8.6.e-2.3.diff.gz

diff --git a/debian/patches/050_bootstrap.diff b/debian/patches/050_bootstrap.diff
--- a/debian/patches/050_bootstrap.diff
+++ b/debian/patches/050_bootstrap.diff
@@ -1,8 +1,63 @@
-Index: vlc-0.8.6.a.debian/configure
+Index: vlc-0.8.6.e/configure
 ===================================================================
---- vlc-0.8.6.a.debian.orig/configure	2007-03-17 00:16:23.000000000 +0100
-+++ vlc-0.8.6.a.debian/configure	2007-03-17 00:17:21.000000000 +0100
-@@ -2952,10 +2952,6 @@
+--- vlc-0.8.6.e.orig/configure	2008-02-24 20:07:09.000000000 +0100
++++ vlc-0.8.6.e/configure	2008-05-15 07:52:39.532607714 +0200
+@@ -988,13 +988,13 @@
+ HAS_WIDL_COMPILER_FALSE
+ BUILD_ACTIVEX_TRUE
+ BUILD_ACTIVEX_FALSE
+-FIREFOX_CFLAGS
+-FIREFOX_LIBS
++ICEAPE_CFLAGS
++ICEAPE_LIBS
+ MOZILLA_CONFIG
+ SEAMONKEY_CONFIG
+ XULRUNNER_CONFIG
+-FIREFOX_XPCOM_CFLAGS
+-FIREFOX_XPCOM_LIBS
++ICEAPE_XPCOM_CFLAGS
++ICEAPE_XPCOM_LIBS
+ MOZILLA_NSPR_CFLAGS
+ MOZILLA_NSPR_LIBS
+ NSPR_CFLAGS
+@@ -1091,10 +1091,10 @@
+ GNUTLS_LIBS
+ MIDL
+ WIDL
+-FIREFOX_CFLAGS
+-FIREFOX_LIBS
+-FIREFOX_XPCOM_CFLAGS
+-FIREFOX_XPCOM_LIBS
++ICEAPE_CFLAGS
++ICEAPE_LIBS
++ICEAPE_XPCOM_CFLAGS
++ICEAPE_XPCOM_LIBS
+ MOZILLA_NSPR_CFLAGS
+ MOZILLA_NSPR_LIBS
+ NSPR_CFLAGS
+@@ -1972,14 +1972,13 @@
+   GNUTLS_LIBS linker flags for GNUTLS, overriding pkg-config
+   MIDL        Microsoft IDL compiler (Win32 platform only)
+   WIDL        Wine IDL compiler (requires Wine SDK)
+-  FIREFOX_CFLAGS
+-              C compiler flags for FIREFOX, overriding pkg-config
+-  FIREFOX_LIBS
+-              linker flags for FIREFOX, overriding pkg-config
+-  FIREFOX_XPCOM_CFLAGS
+-              C compiler flags for FIREFOX_XPCOM, overriding pkg-config
+-  FIREFOX_XPCOM_LIBS
+-              linker flags for FIREFOX_XPCOM, overriding pkg-config
++  ICEAPE_CFLAGS
++              C compiler flags for ICEAPE, overriding pkg-config
++  ICEAPE_LIBS linker flags for ICEAPE, overriding pkg-config
++  ICEAPE_XPCOM_CFLAGS
++              C compiler flags for ICEAPE_XPCOM, overriding pkg-config
++  ICEAPE_XPCOM_LIBS
++              linker flags for ICEAPE_XPCOM, overriding pkg-config
+   MOZILLA_NSPR_CFLAGS
+               C compiler flags for MOZILLA_NSPR, overriding pkg-config
+   MOZILLA_NSPR_LIBS
+@@ -3022,11 +3021,6 @@
  
  
  
@@ -10,6 +65,404 @@ Index: vlc-0.8.6.a.debian/configure
 -  enable_maintainer_mode="yes"
 -fi
 -
- 
+-
  { echo "$as_me:$LINENO: checking whether to enable maintainer-specific portions of Makefiles" >&5
  echo $ECHO_N "checking whether to enable maintainer-specific portions of Makefiles... $ECHO_C" >&6; }
+     # Check whether --enable-maintainer-mode was given.
+@@ -6576,7 +6570,7 @@
+   ;;
+ *-*-irix6*)
+   # Find out which ABI we are using.
+-  echo '#line 6579 "configure"' > conftest.$ac_ext
++  echo '#line 6573 "configure"' > conftest.$ac_ext
+   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+   (eval $ac_compile) 2>&5
+   ac_status=$?
+@@ -9215,11 +9209,11 @@
+    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:9218: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:9212: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>conftest.err)
+    ac_status=$?
+    cat conftest.err >&5
+-   echo "$as_me:9222: \$? = $ac_status" >&5
++   echo "$as_me:9216: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s "$ac_outfile"; then
+      # The compiler can only warn and ignore the option if not recognized
+      # So say no if there are warnings other than the usual output.
+@@ -9505,11 +9499,11 @@
+    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:9508: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:9502: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>conftest.err)
+    ac_status=$?
+    cat conftest.err >&5
+-   echo "$as_me:9512: \$? = $ac_status" >&5
++   echo "$as_me:9506: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s "$ac_outfile"; then
+      # The compiler can only warn and ignore the option if not recognized
+      # So say no if there are warnings other than the usual output.
+@@ -9609,11 +9603,11 @@
+    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:9612: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:9606: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>out/conftest.err)
+    ac_status=$?
+    cat out/conftest.err >&5
+-   echo "$as_me:9616: \$? = $ac_status" >&5
++   echo "$as_me:9610: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s out/conftest2.$ac_objext
+    then
+      # The compiler can only warn and ignore the option if not recognized
+@@ -11986,7 +11980,7 @@
+   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
+   lt_status=$lt_dlunknown
+   cat > conftest.$ac_ext <<EOF
+-#line 11989 "configure"
++#line 11983 "configure"
+ #include "confdefs.h"
+ 
+ #if HAVE_DLFCN_H
+@@ -12086,7 +12080,7 @@
+   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
+   lt_status=$lt_dlunknown
+   cat > conftest.$ac_ext <<EOF
+-#line 12089 "configure"
++#line 12083 "configure"
+ #include "confdefs.h"
+ 
+ #if HAVE_DLFCN_H
+@@ -14487,11 +14481,11 @@
+    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:14490: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:14484: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>conftest.err)
+    ac_status=$?
+    cat conftest.err >&5
+-   echo "$as_me:14494: \$? = $ac_status" >&5
++   echo "$as_me:14488: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s "$ac_outfile"; then
+      # The compiler can only warn and ignore the option if not recognized
+      # So say no if there are warnings other than the usual output.
+@@ -14591,11 +14585,11 @@
+    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:14594: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:14588: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>out/conftest.err)
+    ac_status=$?
+    cat out/conftest.err >&5
+-   echo "$as_me:14598: \$? = $ac_status" >&5
++   echo "$as_me:14592: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s out/conftest2.$ac_objext
+    then
+      # The compiler can only warn and ignore the option if not recognized
+@@ -16189,11 +16183,11 @@
+    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:16192: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:16186: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>conftest.err)
+    ac_status=$?
+    cat conftest.err >&5
+-   echo "$as_me:16196: \$? = $ac_status" >&5
++   echo "$as_me:16190: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s "$ac_outfile"; then
+      # The compiler can only warn and ignore the option if not recognized
+      # So say no if there are warnings other than the usual output.
+@@ -16293,11 +16287,11 @@
+    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:16296: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:16290: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>out/conftest.err)
+    ac_status=$?
+    cat out/conftest.err >&5
+-   echo "$as_me:16300: \$? = $ac_status" >&5
++   echo "$as_me:16294: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s out/conftest2.$ac_objext
+    then
+      # The compiler can only warn and ignore the option if not recognized
+@@ -18513,11 +18507,11 @@
+    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:18516: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:18510: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>conftest.err)
+    ac_status=$?
+    cat conftest.err >&5
+-   echo "$as_me:18520: \$? = $ac_status" >&5
++   echo "$as_me:18514: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s "$ac_outfile"; then
+      # The compiler can only warn and ignore the option if not recognized
+      # So say no if there are warnings other than the usual output.
+@@ -18803,11 +18797,11 @@
+    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:18806: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:18800: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>conftest.err)
+    ac_status=$?
+    cat conftest.err >&5
+-   echo "$as_me:18810: \$? = $ac_status" >&5
++   echo "$as_me:18804: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s "$ac_outfile"; then
+      # The compiler can only warn and ignore the option if not recognized
+      # So say no if there are warnings other than the usual output.
+@@ -18907,11 +18901,11 @@
+    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
+    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
+    -e 's:$: $lt_compiler_flag:'`
+-   (eval echo "\"\$as_me:18910: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:18904: $lt_compile\"" >&5)
+    (eval "$lt_compile" 2>out/conftest.err)
+    ac_status=$?
+    cat out/conftest.err >&5
+-   echo "$as_me:18914: \$? = $ac_status" >&5
++   echo "$as_me:18908: \$? = $ac_status" >&5
+    if (exit $ac_status) && test -s out/conftest2.$ac_objext
+    then
+      # The compiler can only warn and ignore the option if not recognized
+@@ -62202,20 +62196,20 @@
+   then
+ 
+ pkg_failed=no
+-{ echo "$as_me:$LINENO: checking for FIREFOX" >&5
+-echo $ECHO_N "checking for FIREFOX... $ECHO_C" >&6; }
++{ echo "$as_me:$LINENO: checking for ICEAPE" >&5
++echo $ECHO_N "checking for ICEAPE... $ECHO_C" >&6; }
+ 
+ if test -n "$PKG_CONFIG"; then
+-    if test -n "$FIREFOX_CFLAGS"; then
+-        pkg_cv_FIREFOX_CFLAGS="$FIREFOX_CFLAGS"
++    if test -n "$ICEAPE_CFLAGS"; then
++        pkg_cv_ICEAPE_CFLAGS="$ICEAPE_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"firefox-plugin\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "firefox-plugin") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"iceape-plugin\"") >&5
++  ($PKG_CONFIG --exists --print-errors "iceape-plugin") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_FIREFOX_CFLAGS=`$PKG_CONFIG --cflags "firefox-plugin" 2>/dev/null`
++  pkg_cv_ICEAPE_CFLAGS=`$PKG_CONFIG --cflags "iceape-plugin" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -62224,16 +62218,16 @@
+ 	pkg_failed=untried
+ fi
+ if test -n "$PKG_CONFIG"; then
+-    if test -n "$FIREFOX_LIBS"; then
+-        pkg_cv_FIREFOX_LIBS="$FIREFOX_LIBS"
++    if test -n "$ICEAPE_LIBS"; then
++        pkg_cv_ICEAPE_LIBS="$ICEAPE_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"firefox-plugin\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "firefox-plugin") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"iceape-plugin\"") >&5
++  ($PKG_CONFIG --exists --print-errors "iceape-plugin") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_FIREFOX_LIBS=`$PKG_CONFIG --libs "firefox-plugin" 2>/dev/null`
++  pkg_cv_ICEAPE_LIBS=`$PKG_CONFIG --libs "iceape-plugin" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -62252,12 +62246,12 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        FIREFOX_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "firefox-plugin"`
++	        ICEAPE_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "iceape-plugin"`
+         else
+-	        FIREFOX_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "firefox-plugin"`
++	        ICEAPE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "iceape-plugin"`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+-	echo "$FIREFOX_PKG_ERRORS" >&5
++	echo "$ICEAPE_PKG_ERRORS" >&5
+ 
+ 	{ echo "$as_me:$LINENO: result: no" >&5
+ echo "${ECHO_T}no" >&6; }
+@@ -62549,27 +62543,27 @@
+ 
+ 
+ else
+-	FIREFOX_CFLAGS=$pkg_cv_FIREFOX_CFLAGS
+-	FIREFOX_LIBS=$pkg_cv_FIREFOX_LIBS
++	ICEAPE_CFLAGS=$pkg_cv_ICEAPE_CFLAGS
++	ICEAPE_LIBS=$pkg_cv_ICEAPE_LIBS
+         { echo "$as_me:$LINENO: result: yes" >&5
+ echo "${ECHO_T}yes" >&6; }
+ 
+ 
+ pkg_failed=no
+-{ echo "$as_me:$LINENO: checking for FIREFOX_XPCOM" >&5
+-echo $ECHO_N "checking for FIREFOX_XPCOM... $ECHO_C" >&6; }
++{ echo "$as_me:$LINENO: checking for ICEAPE_XPCOM" >&5
++echo $ECHO_N "checking for ICEAPE_XPCOM... $ECHO_C" >&6; }
+ 
+ if test -n "$PKG_CONFIG"; then
+-    if test -n "$FIREFOX_XPCOM_CFLAGS"; then
+-        pkg_cv_FIREFOX_XPCOM_CFLAGS="$FIREFOX_XPCOM_CFLAGS"
++    if test -n "$ICEAPE_XPCOM_CFLAGS"; then
++        pkg_cv_ICEAPE_XPCOM_CFLAGS="$ICEAPE_XPCOM_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"firefox-xpcom\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "firefox-xpcom") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"iceape-xpcom\"") >&5
++  ($PKG_CONFIG --exists --print-errors "iceape-xpcom") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_FIREFOX_XPCOM_CFLAGS=`$PKG_CONFIG --cflags "firefox-xpcom" 2>/dev/null`
++  pkg_cv_ICEAPE_XPCOM_CFLAGS=`$PKG_CONFIG --cflags "iceape-xpcom" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -62578,16 +62572,16 @@
+ 	pkg_failed=untried
+ fi
+ if test -n "$PKG_CONFIG"; then
+-    if test -n "$FIREFOX_XPCOM_LIBS"; then
+-        pkg_cv_FIREFOX_XPCOM_LIBS="$FIREFOX_XPCOM_LIBS"
++    if test -n "$ICEAPE_XPCOM_LIBS"; then
++        pkg_cv_ICEAPE_XPCOM_LIBS="$ICEAPE_XPCOM_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"firefox-xpcom\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "firefox-xpcom") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"iceape-xpcom\"") >&5
++  ($PKG_CONFIG --exists --print-errors "iceape-xpcom") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_FIREFOX_XPCOM_LIBS=`$PKG_CONFIG --libs "firefox-xpcom" 2>/dev/null`
++  pkg_cv_ICEAPE_XPCOM_LIBS=`$PKG_CONFIG --libs "iceape-xpcom" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -62606,12 +62600,12 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        FIREFOX_XPCOM_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "firefox-xpcom"`
++	        ICEAPE_XPCOM_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "iceape-xpcom"`
+         else
+-	        FIREFOX_XPCOM_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "firefox-xpcom"`
++	        ICEAPE_XPCOM_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "iceape-xpcom"`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+-	echo "$FIREFOX_XPCOM_PKG_ERRORS" >&5
++	echo "$ICEAPE_XPCOM_PKG_ERRORS" >&5
+ 
+ 	{ echo "$as_me:$LINENO: result: no" >&5
+ echo "${ECHO_T}no" >&6; }
+@@ -63095,13 +63089,13 @@
+ fi
+ 
+ else
+-	FIREFOX_XPCOM_CFLAGS=$pkg_cv_FIREFOX_XPCOM_CFLAGS
+-	FIREFOX_XPCOM_LIBS=$pkg_cv_FIREFOX_XPCOM_LIBS
++	ICEAPE_XPCOM_CFLAGS=$pkg_cv_ICEAPE_XPCOM_CFLAGS
++	ICEAPE_XPCOM_LIBS=$pkg_cv_ICEAPE_XPCOM_LIBS
+         { echo "$as_me:$LINENO: result: yes" >&5
+ echo "${ECHO_T}yes" >&6; }
+ 	:
+ fi
+-        CPPFLAGS="${CPPFLAGS_save} ${FIREFOX_CFLAGS} ${FIREFOX_XPCOM_CFLAGS} ${MOZILLA_NSPR_CFLAGS} ${NSPR_CFLAGS} ${MOZILLA_CPPFLAGS}"
++        CPPFLAGS="${CPPFLAGS_save} ${ICEAPE_CFLAGS} ${ICEAPE_XPCOM_CFLAGS} ${MOZILLA_NSPR_CFLAGS} ${NSPR_CFLAGS} ${MOZILLA_CPPFLAGS}"
+         MOZILLA_REQUIRED_HEADERS=1
+ 
+ for ac_header in mozilla-config.h
+@@ -63457,7 +63451,7 @@
+         fi
+         MOZILLA_REQUIRED_HEADERS=
+         mozilla=:
+-        firefox_include=`pkg-config --variable=includedir firefox-plugin`
++        firefox_include=`pkg-config --variable=includedir iceape-plugin`
+         if test -f "${firefox_include}/mozilla-config.h" -a -f "${firefox_include}/mozilla-config32.h"; then
+             MOZILLA_CONFIG_H="${firefox_include}/mozilla-config32.h"
+         elif test -f "${firefox_include}/mozilla-config.h" -a -f "${firefox_include}/mozilla-config64.h"; then
+@@ -63481,7 +63475,7 @@
+ 
+ 
+   for element in mozilla; do
+-    eval "LDFLAGS_${element}="'"'"${FIREFOX_LIBS} ${MOZILLA_NSPR_LIBS} ${NSPR_LIBS} ${MOZILLA_LDFLAGS} "'$'"{LDFLAGS_${element}} "'"'
++    eval "LDFLAGS_${element}="'"'"${ICEAPE_LIBS} ${MOZILLA_NSPR_LIBS} ${NSPR_LIBS} ${MOZILLA_LDFLAGS} "'$'"{LDFLAGS_${element}} "'"'
+     am_modules_with_ldflags="${am_modules_with_ldflags} ${element}"
+   done
+ 
+@@ -64604,7 +64598,7 @@
+ JAVA_TEST=Test.java
+ CLASS_TEST=Test.class
+ cat << \EOF > $JAVA_TEST
+-/* #line 64607 "configure" */
++/* #line 64601 "configure" */
+ public class Test {
+ }
+ EOF
+@@ -64780,7 +64774,7 @@
+ if uudecode$EXEEXT Test.uue; then
+         ac_cv_prog_uudecode_base64=yes
+ else
+-        echo "configure: 64783: uudecode had trouble decoding base 64 file 'Test.uue'" >&5
++        echo "configure: 64777: uudecode had trouble decoding base 64 file 'Test.uue'" >&5
+         echo "configure: failed file was:" >&5
+         cat Test.uue >&5
+         ac_cv_prog_uudecode_base64=no
+@@ -64902,7 +64896,7 @@
+ JAVA_TEST=Test.java
+ CLASS_TEST=Test.class
+ cat << \EOF > $JAVA_TEST
+-/* #line 64905 "configure" */
++/* #line 64899 "configure" */
+ public class Test {
+ }
+ EOF
+@@ -64939,7 +64933,7 @@
+ CLASS_TEST=Test.class
+ TEST=Test
+ cat << \EOF > $JAVA_TEST
+-/* [#]line 64942 "configure" */
++/* [#]line 64936 "configure" */
+ public class Test {
+ public static void main (String args[]) {
+         System.exit (0);
+@@ -66978,13 +66972,13 @@
+ HAS_WIDL_COMPILER_FALSE!$HAS_WIDL_COMPILER_FALSE$ac_delim
+ BUILD_ACTIVEX_TRUE!$BUILD_ACTIVEX_TRUE$ac_delim
+ BUILD_ACTIVEX_FALSE!$BUILD_ACTIVEX_FALSE$ac_delim
+-FIREFOX_CFLAGS!$FIREFOX_CFLAGS$ac_delim
+-FIREFOX_LIBS!$FIREFOX_LIBS$ac_delim
++ICEAPE_CFLAGS!$ICEAPE_CFLAGS$ac_delim
++ICEAPE_LIBS!$ICEAPE_LIBS$ac_delim
+ MOZILLA_CONFIG!$MOZILLA_CONFIG$ac_delim
+ SEAMONKEY_CONFIG!$SEAMONKEY_CONFIG$ac_delim
+ XULRUNNER_CONFIG!$XULRUNNER_CONFIG$ac_delim
+-FIREFOX_XPCOM_CFLAGS!$FIREFOX_XPCOM_CFLAGS$ac_delim
+-FIREFOX_XPCOM_LIBS!$FIREFOX_XPCOM_LIBS$ac_delim
++ICEAPE_XPCOM_CFLAGS!$ICEAPE_XPCOM_CFLAGS$ac_delim
++ICEAPE_XPCOM_LIBS!$ICEAPE_XPCOM_LIBS$ac_delim
+ MOZILLA_NSPR_CFLAGS!$MOZILLA_NSPR_CFLAGS$ac_delim
+ MOZILLA_NSPR_LIBS!$MOZILLA_NSPR_LIBS$ac_delim
+ NSPR_CFLAGS!$NSPR_CFLAGS$ac_delim
